"""empty message

Revision ID: 7e7166934fcb
Revises: 841daa32397c
Create Date: 2020-09-21 12:18:04.413807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7166934fcb'
down_revision = '841daa32397c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist_Genre',
    sa.Column('genre_type', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.PrimaryKeyConstraint('genre_type', 'artist_id')
    )
    op.create_table('Venue_Genre',
    sa.Column('genre_type', sa.String(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('genre_type', 'venue_id')
    )
    op.add_column('Artist', sa.Column('availability', sa.Boolean(), nullable=True))
    op.drop_column('Artist', 'genres')
    op.add_column('Venue', sa.Column('availability', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'availability')
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('Artist', 'availability')
    op.drop_table('Venue_Genre')
    op.drop_table('Artist_Genre')
    # ### end Alembic commands ###
